name: CI Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ master ]
  workflow_dispatch:
permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
  # iOS MAUI Build Job
  build-ios:
    runs-on: macos-latest
    name: iOS Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Install MAUI workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore dependencies
        run: dotnet restore MaoMao/MaoMao.csproj

      - name: Build iOS IPA
        run: dotnet build MaoMao/MaoMao.csproj -c Release -f net8.0-ios /p:RuntimeIdentifier=ios-arm64 /p:BuildIpa=true /p:ArchiveOnBuild=true /p:EnableCodeSigning=false

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: maomao-ios-ipa
          path: MaoMao/bin/Release/net8.0-ios/ios-arm64/**/*.ipa
